theme: minima
title: ICS4U Portfolio00
author: Lydia
email: lroy1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio project for ICS4U.




show_excerpts: false # set to false to remove excerpts on the homepage
